ALTER SESSION SET CURRENT_SCHEMA = OLIMPIA;

SELECT NEV FROM O_VERSENYZOK ORDER BY NEV;

SELECT * FROM O_VERSENYZOK;

SELECT ROUND((SYSDATE - SZUL_DAT)/365,1) AS eletkor FROM o_VERSENYZOK WHERE SZUL_DAT IS NOT NULL;

SELECT * FROM O_ORSZAGOK;

SELECT ROUND(SUM(LAKOSSAG)/SUM(TERULET),2) AS NEPSURUSEG,COUNT(ORSZAG), FOLDRESZ FROM O_ORSZAGOK GROUP BY FOLDRESZ ORDER BY COUNT(ORSZAG) DESC;

SELECT * FROM O_EREM_TABLA;
SELECT * FROM O_EREDMENYEK;

SELECT DISTINCT(NEV), HELYEZES FROM (SELECT * FROM O_EREDMENYEK JOIN O_VERSENYZOK ON O_EREDMENYEK.VERSENYZO_AZON = O_VERSENYZOK.AZON) WHERE HELYEZES <=3;

SELECT ARANY+EZUST+BRONZ AS DOBOGOS, ORSZAG
FROM (SELECT * FROM O_EREM_TABLA JOIN O_ORSZAGOK ON O_EREM_TABLA.ORSZAG_AZON = O_ORSZAGOK.AZON) ORDER BY (ARANY+EZUST+BRONZ);

SELECT ORSZAG FROM O_ORSZAGOK WHERE TERULET > (SELECT AVG(TERULET) FROM O_ORSZAGOK) AND LAKOSSAG < (SELECT AVG(LAKOSSAG) FROM O_ORSZAGOK);

SELECT ORSZAG
FROM (SELECT * FROM O_EREDMENYEK JOIN O_VERSENYZOK ON O_EREDMENYEK.VERSENYZO_AZON = O_VERSENYZOK.AZON 
JOIN O_ORSZAGOK ON O_VERSENYZOK.ORSZAG_AZON = O_ORSZAGOK.AZON) WHERE HELYEZES IS NOT NULL ORDER BY HELYEZES DESC FETCH FIRST 1 ROWS ONLY;

SELECT COUNT(HELYEZES),VERSENYZO_AZON FROM O_EREDMENYEK WHERE HELYEZES = 1 GROUP BY VERSENYZO_AZON;

SELECT ORSZAG_AZON, VERSENYZO_AZON FROM O_EREDMENYEK JOIN O_VERSENYZOK ON O_EREDMENYEK.VERSENYZO_AZON = O_VERSENYZOK.AZON WHERE HELYEZES = 1;

SELECT DISTINCT VERSENYZO_AZON, VERSENYSZAM_AZON FROM O_EREDMENYEK WHERE HELYEZES <4;

SELECT COUNT(*) FROM O_EREDMENYEK JOIN O_VERSENYSZAMOK ON O_EREDMENYEK.VERSENYSZAM_AZON = O_VERSENYSZAMOK.AZON WHERE HELYEZES <4 and FERFI_NOI='nõi';



